# Project Name
TARGET = slipRecorder

# Sources
CPP_SOURCES = slipRecorder.cpp

# Add FatFS unicode support for code page 850 (Latin 1)
C_SOURCES = $(LIBDAISY_DIR)/Middlewares/Third_Party/FatFs/src/option/ccsbcs.c

include ../../common.mk

