# Project Name
TARGET = multiFxTemplate

# Set the C++ standard
CPP_STANDARD = -std=gnu++14

# Set optimization level
OPT=-Ofast

# Set App Type
APP_TYPE = BOOT_SRAM

# Sources
CPP_SOURCES = multiFxTemplate.cpp

include ../../common.mk
