# Project Name
TARGET = main

# Set the C++ standard
CPP_STANDARD = -std=gnu++14

# Set optimization level
OPT=-Ofast

# Set App Type
APP_TYPE = BOOT_SRAM

# Sources
CPP_SOURCES = main.cpp

include ../../common.mk
