# Project Name
TARGET = cpuLoadTest

# Sources
CPP_SOURCES = cpuLoadTest.cpp

# Library Locations
LIBDAISY_DIR = ../../libDaisy

# Core location, and generic makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile

