# Project Name
TARGET = main

# Set the C++ standard
CPP_STANDARD = -std=gnu++14

# Set optimization level
OPT=-Ofast

# Set App Type
APP_TYPE = BOOT_SRAM

# Set Boot Bin to 10ms version (default is 2000ms)
BOOT_BIN = $(SYSTEM_FILES_DIR)/dsy_bootloader_v6_2-intdfu-10ms.bin

# Sources
CPP_SOURCES = main.cpp

include ../../common.mk
