# Project Name
TARGET = namTest

CPP_STANDARD = -std=gnu++14
OPT=-Ofast

# Set App Type
APP_TYPE = BOOT_SRAM

# Set Boot Bin to 10ms version (default is 2000ms)
BOOT_BIN = $(SYSTEM_FILES_DIR)/dsy_bootloader_v6_2-intdfu-10ms.bin

# Sources
CPP_SOURCES = namTest.cpp

include ../../common.mk

